chore(deps): bump up to latest minor version except typescript
typescript@5.3.2 caused build failure so kept it @5.2.2.
See below (paths truncated to keep husky happy):

  $ pnpm build

  > oit@15.1.4 build /oit
  > vue-tsc --noEmit && vite build

  node_modules/.pnpm/typescript@5.3.2/...
            throw e;
            ^

  Error: Debug Failure. Expected undefined === 2.
      at acquireOrUpdateDocument (node_modules/.pnpm/typescript@5.3.2/...)
      at Object.acquireDocumentWithKey (node_modules/.pnpm/typescript@5.3.2/...)
      at getOrCreateSourceFileByPath (node_modules/.pnpm/typescript@5.3.2/...)
      at Object.getOrCreateSourceFile (node_modules/.pnpm/typescript@5.3.2/...)
      at node_modules/.pnpm/typescript@5.3.2/...
      at Object.getSourceFileWithCache [as getSourceFile] (node_modules/.pnpm/typescript@5.3.2/...)
      at findSourceFileWorker (node_modules/.pnpm/typescript@5.3.2/...)
      at findSourceFile (node_modules/.pnpm/typescript@5.3.2/...)
      at node_modules/.pnpm/typescript@5.3.2/...
      at getSourceFileFromReferenceWorker (node_modules/.pnpm/typescript@5.3.2/...)